app: myapp
service: hello-world

stages: 
  dev01:
    observability: false

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30  
  stage: dev01
  region: us-west-2
  tags:
    App: "${self:app}"

custom:
  duplocloud:
    tenant: ${opt:stage}
    usePrefix: true

functions:
  helloworld:
    description: Hello world
    handler: index.handler

plugins:
- serverless-duplocloud
