name: Pull Request

on:
  pull_request:
    branches:
    - main

jobs: 

  changelog_check:
    name: Changelog Updated
    runs-on: ubuntu-latest
    steps:
    - name: Make sure changes are logged
      uses: tarides/changelog-check-action@v3
      with:
        changelog: CHANGELOG.md

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
    - name: Setup
      id: setup
      uses: duplocloud/serverless/.github/actions/setup@main
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}
    # download the coverage report artifact
    - name: Download coverage report
      uses: actions/download-artifact@v4
      with:
        name: coverage
        path: coverage
    - name: Info
      run: ls -al coverage
    # - name: Upload coverage report
    #   uses: vebr/jest-lcov-reporter@v0.2.0
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     lcov-file: ./coverage/lcov.info
    - name: Upload coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        # github-token: ${{ steps.setup.outputs.token }}
        skip-step: all
        coverage-file: ./coverage/coverage-final.json
        base-coverage-file: ./coverage/coverage-final.json
