name: Release Version

# on tags starting with a v, e.g. v1.0.0
on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Download Package
      uses: actions/download-artifact@v4
      with:
        name: package
        path: dist
        
    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: false
        make_latest: true
        generate_release_notes: true
        files: |
          dist/*
        body: |

          [![Publish](${{ github.server_url }}/${{ github.repository }}/actions/workflows/release.yml/badge.svg)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
